# Generated by Django 3.2.16 on 2023-03-04 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallpage', '0003_auto_20230226_2107'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followers', models.CharField(max_length=200)),
                ('following', models.CharField(max_length=200)),
            ],
        ),
    ]
